env: safetyGraphics
label: Adverse Event Explorer
type: htmlwidget
package: safetyCharts  
export: true
order: 2
domain: 
  - dm
  - aes
dataSpec:
  dm:
    - id_col
    - treatment_col
  aes:
    - id_col
    - term_col
    - bodsys_col
workflow:
  init: init_aeExplorer
  widget: aeExplorer
links:
  Homepage: https://github.com/RhoInc/aeexplorer
  Wiki: https://github.com/RhoInc/aeexplorer/wiki 
  Issues: https://github.com/RhoInc/aeexplorer/issues
  Demo: https://rhoinc.github.io/aeexplorer/test-page/
  safetyCharts: https://github.com/SafetyGraphics/safetycharts

