env: safetyGraphics
label: Conmeds Explorer
type: htmlwidget
package: safetyCharts  
export: true
order: 2
domain: 
  dm:
    - id_col
    - treatment_col
  cm:
    - id_col
    - class_col
    - code_col
workflow:
  init: init_cmExplorer
  widget: aeExplorer
links:
  Homepage: https://github.com/RhoInc/aeexplorer
  Wiki: https://github.com/RhoInc/aeexplorer/wiki 
  Issues: https://github.com/RhoInc/aeexplorer/issues
  Demo: https://rhoinc.github.io/aeexplorer/test-page/
  safetyCharts: https://github.com/SafetyGraphics/safetycharts
