env: safetyGraphics
label: Com Meds Timelines
type: htmlwidget
package: safetyCharts
export: false 
order: 3
domain: 
  - cm
dataSpec:
  cm:
    - id_col
    - stdy_col
    - endy_col
    - seq_col
    - code_col
    - indication_col
workflow:
  init: init_cmTimelines
  widget: aeTimelines
links:
  Homepage: https://github.com/RhoInc/ae-timelines
  Wiki: https://github.com/RhoInc/ae-timelines/wiki 
  Issues: https://github.com/RhoInc/ae-timelines/issues
  Demo: https://rhoinc.github.io/ae-timelines/test-page/
  safetyCharts: https://github.com/SafetyGraphics/safetycharts

