env: safetyGraphics
label: Demographics Table
type: module
package: safetyCharts
export: false
order: 1
domain: 
  - dm
dataSpec:
  dm:
    - id_col
    - treatment_col
    - age_col
    - sex_col
    - race_col
workflow:
  server: demogRTF_server
  ui: demogRTF_ui
links: 
  Tplyr: https://CRAN.R-project.org/package=Tplyr 
  huxtable: https://CRAN.R-project.org/package=huxtable  
  pharmaRTF: https://CRAN.R-project.org/package=pharmaRTF 
