env: safetyGraphics
label: Demographics Table
type: module
order: 1
domain: 
  - dm
package: safetyCharts
workflow:
  server: demogRTF_server
  ui: demogRTF_ui
links: 
  Tplyr: https://CRAN.R-project.org/package=Tplyr 
  huxtable: https://CRAN.R-project.org/package=huxtable  
  pharmaRTF: https://CRAN.R-project.org/package=pharmaRTF 
