env: safetyGraphics
label: Hepatic Safety Explorer
type: htmlwidget
package: safetyCharts  
domain: 
  - labs
export: true
workflow:
  widget: hepexplorer
links:
  Homepage: https://github.com/SafetyGraphics/hep-explorer
  Wiki: https://github.com/SafetyGraphics/hep-explorer/wiki 
  Issues: https://github.com/SafetyGraphics/hep-explorer/issues
  Demo: https://safetygraphics.github.io/hep-explorer/test-page/example1/
  safetyCharts: https://github.com/SafetyGraphics/safetycharts

