env: safetyGraphics
label: Labs Distribution
type: module
domain: labs
package: safetyCharts
export: false
workflow:
  ui: lab_distribution_ui
  server: lab_distribution_server
links:
  safetyCharts: https://github.com/SafetyGraphics/safetycharts
