env: safetyGraphics
label: Labs Distribution
type: module
package: safetyCharts
domain: 
  - labs
export: false
order: -1
workflow:
  ui: lab_distribution_ui
  server: lab_distribution_server
links:
  safetyCharts: https://github.com/SafetyGraphics/safetycharts
