env: safetyGraphics
label: Medical History Explorer
type: htmlwidget
package: safetyCharts  
export: true
order: 2.2
domain:
  - dm
  - mh
dataSpec: 
  dm:
    - id_col
    - treatment_col
  mh:
    - id_col
    - class_col
    - code_col
workflow:
  init: init_mhExplorer
  widget: aeExplorer
links:
  Homepage: https://github.com/RhoInc/aeexplorer
  Wiki: https://github.com/RhoInc/aeexplorer/wiki 
  Issues: https://github.com/RhoInc/aeexplorer/issues
  Demo: https://rhoinc.github.io/aeexplorer/test-page/
  safetyCharts: https://github.com/SafetyGraphics/safetycharts
