env: safetyGraphics
label: RTF Renderer {Tplyr} + {huxtable} + {pharmaRTF}
type: rtf
domain: dm
package: safetyCharts
workflow:
  main: pharmartf_render_table
links: 
  Tplyr: https://CRAN.R-project.org/package=Tplyr 
  huxtable: https://CRAN.R-project.org/package=huxtable  
  pharmaRTF: https://CRAN.R-project.org/package=pharmaRTF 
