env: safetyGraphics
label: Outlier Explorer - Module
type: module
package: safetyCharts
export: false
order: -1
domain: 
  - labs
workflow:
  ui: safetyOutlierExplorer_ui
  server: safetyOutlierExplorer_server
links:
  safetyCharts: https://github.com/SafetyGraphics/safetycharts
