env: safetyGraphics
label: Outlier Explorer
type: plot
package: safetyCharts
export: true
order: -1
domain: 
  - labs
workflow:
  main: safety_outlier_explorer
links:
  safetyCharts: https://github.com/SafetyGraphics/safetycharts
