env: safetyGraphics
label: Vitals Over Time
type: htmlwidget
package: safetyCharts
export: true
domain: 
  - vitals
dataSpec:
  vitals:
    - id_col
    - visit_col
    - visitn_col
    - measure_col
    - value_col
workflow:
  init: init_safetyResultsOverTime
  widget: safetyResultsOverTime
links:
  Homepage: https://github.com/RhoInc/safety-results-over-time
  Wiki: https://github.com/RhoInc/safety-results-over-time/wiki
  Issues: https://github.com/RhoInc/safety-results-over-time/issues
  Demo: https://rhoinc.github.io/safety-results-over-time/test-page/
  safetyCharts: https://github.com/SafetyGraphics/safetycharts
