env: safetyGraphics
label: Shift Plot
type: htmlwidget
package: safetyCharts
export: true
order: 9
domain: 
  - labs
dataSpec:
  labs:
    - id_col
    - visit_col
    - visitn_col
    - measure_col
    - value_col
workflow:
  init: init_safetyShiftPlot
  widget: safetyShiftPlot
links:
  Homepage: https://github.com/RhoInc/safety-shift-plot
  Wiki: https://github.com/RhoInc/safety-shift-plot/wiki 
  Issues: https://github.com/RhoInc/safety-shift-plot/issues
  Demo: https://rhoinc.github.io/safety-shift-plot/test-page/
  safetyCharts: https://github.com/SafetyGraphics/safetycharts

