env: safetyGraphics
label: Results Over Time
type: plot
package: safetyCharts
export: true
order: -1
domain: 
  - labs
workflow:
  main: safety_results_over_time
links:
  safetyCharts: https://github.com/SafetyGraphics/safetycharts
