env: safetyGraphics
label: Outlier Explorer - Static
type: plot
domain: labs
package: safetyCharts
export: true
workflow:
  main: safety_outlier_explorer
links:
  safetyCharts: https://github.com/SafetyGraphics/safetycharts
