env: safetyGraphics
label: Histogram
type: htmlwidget
package: safetyCharts
domain: 
  - labs
dataSpec:
  labs:
    - id_col
    - measure_col
    - value_col
    - normal_col_low
    - normal_col_high
export: true
workflow:
  widget: safetyHistogram
links:
  Homepage: https://github.com/RhoInc/safety-histogram
  Wiki: https://github.com/RhoInc/safety-histogram/wiki 
  Issues: https://github.com/RhoInc/safety-histogram/issues
  Demo: https://rhoinc.github.io/safety-histogram/test-page/
  safetyCharts: https://github.com/SafetyGraphics/safetycharts

