env: safetyGraphics
label: Outlier Explorer - Module
type: module
domain: labs
package: safetyCharts
export: false
workflow:
  ui: safetyOutlierExplorer_ui
  server: safetyOutlierExplorer_server
links:
  safetyCharts: https://github.com/SafetyGraphics/safetycharts
