env: safetyGraphics
label: Outlier Explorer
type: plot
package: safetyCharts
export: true
order: -1
domain: 
  - labs
dataSpec:
  labs:
    - id_col
    - studyday_col
    - measure_col
    - value_col
workflow:
  main: safety_outlier_explorer
links:
  safetyCharts: https://github.com/SafetyGraphics/safetycharts
