env: safetyGraphics
label: Tendril Plot
type: plot
package: safetyCharts
export: true
order: 9999
domain: 
  - dm
  - aes
dataSpec:
  dm:
    - id_col
    - treatment_col
  aes:
    - id_col
    - stdy_col
    - endy_col
    - bodsys_col
workflow:
  main: tendril_chart
links: 
  tendril: https://cran.r-project.org/package=Tendril
