env: safetyGraphics
label: Tendril Plot
type: plot
package: safetyCharts
export: true
order: 4
domain: 
  - aes
  - dm
workflow:
  main: tendril_chart
links: 
  tendril: https://cran.r-project.org/package=Tendril
