env: safetyGraphics
label: Tendril Plot
type: plot
domain: 
  - aes
  - dm
package: safetyCharts
export: true
workflow:
  main: tendril_chart
links: 
  tendril: https://cran.r-project.org/package=Tendril
