env: safetyGraphics
label: Shift Table
type: html
package: safetyCharts
order: -1
domain: 
  - labs
  - dm
workflow:
  main: tplyr_shift_chart
links: 
  Tplyr: https://CRAN.R-project.org/package=Tplyr 
  kable: https://cran.r-project.org/package=knitr
