env: safetyGraphics
label: Shift Table
type: html
domain: 
  - labs
  - dm
package: safetyCharts
workflow:
  main: tplyr_shift_chart
links: 
  Tplyr: https://CRAN.R-project.org/package=Tplyr 
  kable: https://cran.r-project.org/package=knitr
