env: safetyGraphics
label: Shift Table
type: html
domain: multiple
package: safetyCharts
workflow:
  main: tplyr_shift_chart
links: 
  Tplyr: https://CRAN.R-project.org/package=Tplyr 
  kable: https://CRAN.R-project.org/package=kable  

