env: safetyGraphics
label: Demographics Table
type: table
package: safetyCharts
export: true
order: -1
domain: 
  - dm
workflow:
  main: tplyr_demog_chart
links: 
  Tplyr: https://CRAN.R-project.org/package=Tplyr 
  DT: https://CRAN.R-project.org/package=DT
